export type CallingCode = { code: string; name: string; iso2: string };
export const CALLING_CODES: CallingCode[] = [
  { code: '+1', name: 'United States', iso2: 'US' },
  { code: '+1', name: 'Canada', iso2: 'CA' },
  { code: '+44', name: 'United Kingdom', iso2: 'GB' },
  { code: '+91', name: 'India', iso2: 'IN' },
  { code: '+971', name: 'United Arab Emirates', iso2: 'AE' },
  { code: '+61', name: 'Australia', iso2: 'AU' },
  { code: '+81', name: 'Japan', iso2: 'JP' },
  { code: '+49', name: 'Germany', iso2: 'DE' },
  { code: '+33', name: 'France', iso2: 'FR' },
  { code: '+39', name: 'Italy', iso2: 'IT' },
  { code: '+34', name: 'Spain', iso2: 'ES' },
  { code: '+65', name: 'Singapore', iso2: 'SG' },
  { code: '+966', name: 'Saudi Arabia', iso2: 'SA' },
  { code: '+974', name: 'Qatar', iso2: 'QA' },
  { code: '+973', name: 'Bahrain', iso2: 'BH' },
  { code: '+968', name: 'Oman', iso2: 'OM' },
  { code: '+852', name: 'Hong Kong', iso2: 'HK' },
  { code: '+886', name: 'Taiwan', iso2: 'TW' },
  { code: '+86', name: 'China', iso2: 'CN' },
  { code: '+92', name: 'Pakistan', iso2: 'PK' },
  { code: '+94', name: 'Sri Lanka', iso2: 'LK' },
  { code: '+880', name: 'Bangladesh', iso2: 'BD' },
  { code: '+7', name: 'Russia', iso2: 'RU' },
  { code: '+55', name: 'Brazil', iso2: 'BR' },
  { code: '+57', name: 'Colombia', iso2: 'CO' },
  { code: '+56', name: 'Chile', iso2: 'CL' },
  { code: '+964', name: 'Iraq', iso2: 'IQ' },
  { code: '+20', name: 'Egypt', iso2: 'EG' },
  { code: '+27', name: 'South Africa', iso2: 'ZA' },
  { code: '+62', name: 'Indonesia', iso2: 'ID' },
  { code: '+63', name: 'Philippines', iso2: 'PH' },
  { code: '+60', name: 'Malaysia', iso2: 'MY' },
  { code: '+66', name: 'Thailand', iso2: 'TH' },
  { code: '+84', name: 'Vietnam', iso2: 'VN' },
  { code: '+853', name: 'Macau', iso2: 'MO' },
  { code: '+90', name: 'Turkey', iso2: 'TR' },
  { code: '+98', name: 'Iran', iso2: 'IR' },
  { code: '+970', name: 'Palestine', iso2: 'PS' },
  { code: '+962', name: 'Jordan', iso2: 'JO' },
  { code: '+961', name: 'Lebanon', iso2: 'LB' },
  { code: '+963', name: 'Syria', iso2: 'SY' },
  { code: '+212', name: 'Morocco', iso2: 'MA' },
  { code: '+213', name: 'Algeria', iso2: 'DZ' },
  { code: '+216', name: 'Tunisia', iso2: 'TN' },
  { code: '+971', name: 'United Arab Emirates', iso2: 'AE' },
  { code: '+354', name: 'Iceland', iso2: 'IS' },
  { code: '+353', name: 'Ireland', iso2: 'IE' },
  { code: '+47', name: 'Norway', iso2: 'NO' },
  { code: '+46', name: 'Sweden', iso2: 'SE' },
  { code: '+45', name: 'Denmark', iso2: 'DK' },
  { code: '+31', name: 'Netherlands', iso2: 'NL' },
  { code: '+32', name: 'Belgium', iso2: 'BE' },
  { code: '+41', name: 'Switzerland', iso2: 'CH' },
  { code: '+43', name: 'Austria', iso2: 'AT' },
  { code: '+48', name: 'Poland', iso2: 'PL' },
  { code: '+420', name: 'Czechia', iso2: 'CZ' },
  { code: '+421', name: 'Slovakia', iso2: 'SK' },
  { code: '+36', name: 'Hungary', iso2: 'HU' },
  { code: '+40', name: 'Romania', iso2: 'RO' },
  { code: '+380', name: 'Ukraine', iso2: 'UA' },
  { code: '+375', name: 'Belarus', iso2: 'BY' },
  { code: '+371', name: 'Latvia', iso2: 'LV' },
  { code: '+370', name: 'Lithuania', iso2: 'LT' },
  { code: '+372', name: 'Estonia', iso2: 'EE' },
  { code: '+351', name: 'Portugal', iso2: 'PT' },
  { code: '+30', name: 'Greece', iso2: 'GR' },
  { code: '+380', name: 'Ukraine', iso2: 'UA' },
  { code: '+52', name: 'Mexico', iso2: 'MX' },
  { code: '+54', name: 'Argentina', iso2: 'AR' },
  { code: '+51', name: 'Peru', iso2: 'PE' },
  { code: '+58', name: 'Venezuela', iso2: 'VE' },
  { code: '+505', name: 'Nicaragua', iso2: 'NI' },
  { code: '+507', name: 'Panama', iso2: 'PA' },
  { code: '+593', name: 'Ecuador', iso2: 'EC' },
  { code: '+502', name: 'Guatemala', iso2: 'GT' },
  { code: '+503', name: 'El Salvador', iso2: 'SV' },
  { code: '+504', name: 'Honduras', iso2: 'HN' },
  { code: '+506', name: 'Costa Rica', iso2: 'CR' },
  { code: '+1-876', name: 'Jamaica', iso2: 'JM' },
  { code: '+64', name: 'New Zealand', iso2: 'NZ' },
  { code: '+82', name: 'South Korea', iso2: 'KR' },
  { code: '+86', name: 'China', iso2: 'CN' },
  { code: '+880', name: 'Bangladesh', iso2: 'BD' },
  { code: '+94', name: 'Sri Lanka', iso2: 'LK' },
  { code: '+977', name: 'Nepal', iso2: 'NP' },
  { code: '+975', name: 'Bhutan', iso2: 'BT' },
  { code: '+960', name: 'Maldives', iso2: 'MV' },
  { code: '+92', name: 'Pakistan', iso2: 'PK' },
  { code: '+98', name: 'Iran', iso2: 'IR' },
  { code: '+20', name: 'Egypt', iso2: 'EG' },
  { code: '+251', name: 'Ethiopia', iso2: 'ET' },
  { code: '+254', name: 'Kenya', iso2: 'KE' },
  { code: '+255', name: 'Tanzania', iso2: 'TZ' },
  { code: '+256', name: 'Uganda', iso2: 'UG' },
  { code: '+263', name: 'Zimbabwe', iso2: 'ZW' },
  { code: '+234', name: 'Nigeria', iso2: 'NG' },
  { code: '+233', name: 'Ghana', iso2: 'GH' },
  { code: '+221', name: 'Senegal', iso2: 'SN' },
  { code: '+27', name: 'South Africa', iso2: 'ZA' },
  { code: '+213', name: 'Algeria', iso2: 'DZ' },
  { code: '+216', name: 'Tunisia', iso2: 'TN' },
  { code: '+212', name: 'Morocco', iso2: 'MA' },
];
